language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: 
    recipients:
      - dwalter@barlingarts.com
node_js:
  - '7'
before_script:
  - npm prune
script:
  - npm test
  - npm run prod
after_success:
  - npm version minor 
branches:
  only:
    - master
